### ISSUE TITLE
Implement a structure for CRUD operations within the application.

### ISSUE THREAD

**Issue by gian7sm** [CultureFoundryCA/WebModules#16]
We need to define how CRUD (create, read, update, delete) operations will be implemented in the application to ensure transactional integrity and test these operations in our test database.

**Comment by gian7sm** [comment]
@scott-parkhill, I will leave this one open for you to complete CRUD operations. Moving it to Sprint 2

**Comment by scott-parkhill** [comment]
Close as per discussion and web module development.
