### ISSUE TITLE
Only show modules that are accessible by the user in the index razor component.

### ISSUE THREAD

**Issue by scott-parkhill** [CultureFoundryCA/WebModules#48]
Need help understanding use of AppUserId cascading parameter use in database lookup in order to implement this feature.

**Comment by gian7sm** [comment]
@scott-parkhill , The index page should still display available modules (maybe all of them or at least some), but each module should have a visual indicator for locked/unlocked   (like those existing icons)  as it corresponds to each user.
To get the logged used ID as a parameter, we'll need to make the index page accessible to authenticated users only.
