### ISSUE TITLE
Fix display bug and profile editing redirect for users that didn't put in clan etc info

### ISSUE THREAD

**Issue by scott-parkhill** [CultureFoundryCA/WebModules#58]
As it stands, if you haven't put in your name or clan information, it just displays "<>", and when you click on your profile, it throws an error. It seems to be something wrong with line 158 in the ProfileComponent.razor? I'm not sure how to fix it.

**Comment by gian7sm** [comment]
@scott-parkhill, the commits on Feb 22 from 2fc3cdd0f5a3f49337c706a2bf34461a6bb8536f to 61df3af7d4689fcda9cd70434a10edf3c0af9b82 should have corrected this behavior

**Comment by scott-parkhill** [comment]
@gian7sm Will review and close.
