### ISSUE TITLE
When the 'next' button appears in the gaps game, the banner that the words sits in moves down, so the text ends up partially outside of the background

### ISSUE THREAD

**Issue by scott-parkhill** [CultureFoundryCA/WebModules#63]

**Comment by gian7sm** [comment]
@legoodyearrr , I've made the gaps activity to always display the button (inside a row div) so it always stays rendered. It gets enabled and disabled. Let me know if that works for you. If the button is styled so the user can tell when the button is clickable, that should do it.
If you have something else in mind, let me know :)
