### ISSUE TITLE
A card slot disappeared when moving the cards around on top of each other or something. Will edit with reproduceability information when I find it. See screenshot.

### ISSUE THREAD

**Issue by scott-parkhill** [CultureFoundryCA/WebModules#74]
![image](https://user-images.githubusercontent.com/48695928/108743190-89f94380-7506-11eb-95cf-63358848c816.png)

**Comment by scott-parkhill** [comment]
Actually, the card has entirely disappeared, and the game is not completeable. I zoomed out all the way and the card cannot be found.

![image](https://user-images.githubusercontent.com/48695928/108744330-ced1aa00-7507-11eb-8589-c29edcd5be72.png)

**Comment by scott-parkhill** [comment]
The card disappeared, but some remnant of it remained. By clicking and draggy in random spots, the card could be "found" and reappear. However, clicking and dragging the card and releasing it again (not into a basket) would make it disappear again, and it would have to be "found" again. It could be found in the same spot, somewhere approximately over the AA basket.

**Comment by scott-parkhill** [comment]
REPRODUCTION INSTRUCTIONS: Drag a card to the left of the leftmost card, just so that it is basically touching the sidebar, and let go, and it will disappear.

**Comment by gian7sm** [comment]
@scott-parkhill the cards were not being properly reset on incorrect drops.
You can review this bug again and close it if it has been fixed please.

**Comment by scott-parkhill** [comment]
@gian7sm Will do. Will do that after the meetings today.
