### ISSUE TITLE
Module 1

### ISSUE THREAD

**Issue by cpquinn** [CultureFoundryCA/WebModules#92]
- [ ] Task1
- [ ] Task 2 #91 
- [x] Task 3 #90

**Comment by gian7sm** [comment]
@cpquinn task lists can help with Epics. I'm adding a sample to the description of this one.
Each task can be an independent issue. So we can have issues that are tasks, and issues that are epics.
The issue that's an epic can have links to the issues that are tasks to oversee them as well.

**Comment by cpquinn** [comment]
Test response via Zenhub.
